/**
 * Mapa nombre -> componente para el banco de iconos de Direccion de grupo
 * (`domain/iconos-direccion.ts`).
 *
 * Los 53 nombres se importan UNO A UNO a proposito. La alternativa —
 * `import * as Lucide from 'lucide-react'` e indexar `(Lucide as any)[nombre]`— mete las
 * 5.885 iconos de la libreria en el bundle principal de MJB, que descarga TODO el mundo
 * (incluidos los docentes que solo pasan lista desde el celular y nunca abren esta
 * pantalla), porque un import de espacio de nombres indexado dinamicamente no se puede
 * podar en el empaquetado. Con imports nombrados, el empaquetador se lleva solo estos 53.
 *
 * Los nombres DEBEN coincidir exactamente con `ICONOS_DIRECCION`. Si se agrega un icono
 * alla, se agrega aqui tambien —y solo aqui, verificando antes que el export existe en
 * lucide-react—.
 */
import {
  Apple,
  Backpack,
  Banknote,
  Bike,
  Book,
  BookOpen,
  Brush,
  Bus,
  Calculator,
  Car,
  Check,
  CircleAlert,
  CircleHelp,
  ClipboardCheck,
  Coins,
  Cross,
  CupSoda,
  Drama,
  Dumbbell,
  Flag,
  Footprints,
  Frown,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Mail,
  Megaphone,
  Meh,
  MessageCircle,
  Microscope,
  Milk,
  Music,
  Palette,
  Pencil,
  Phone,
  Pill,
  Receipt,
  Recycle,
  Smile,
  SprayCan,
  Star,
  Stethoscope,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Trophy,
  Users,
  Utensils,
  Volleyball,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

export const ICONO_COMPONENTE: Record<string, LucideIcon> = {
  Check,
  X,
  Star,
  Flag,
  CircleAlert,
  CircleHelp,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Meh,
  Frown,
  Coins,
  Banknote,
  Wallet,
  Receipt,
  HandCoins,
  Utensils,
  Milk,
  Apple,
  CupSoda,
  HeartPulse,
  Cross,
  Thermometer,
  Pill,
  Stethoscope,
  Brush,
  SprayCan,
  Trash2,
  Recycle,
  Bus,
  Bike,
  Car,
  Footprints,
  Book,
  BookOpen,
  Pencil,
  GraduationCap,
  ClipboardCheck,
  Backpack,
  Calculator,
  Microscope,
  Music,
  Palette,
  Trophy,
  Volleyball,
  Dumbbell,
  Drama,
  Phone,
  Mail,
  MessageCircle,
  Megaphone,
  Users,
  House,
};
